#!/usr/bin/env sh
set -eu
repo=${COMPACTVETERAN_REPO:-lmtlssss/CompactVeteran}; codex_home=${CODEX_HOME:-$HOME/.codex}; data=$codex_home/plugins/data/compactveteran-compactveteran; state=${XDG_STATE_HOME:-$HOME/.local/state}/compactveteran/install; bin=$HOME/.local/bin/codex
command -v codex >/dev/null; command -v curl >/dev/null; test "$(uname -s)" = Linux && test "$(uname -m)" = x86_64
stock=$codex_home/packages/standalone/current/bin/codex; test -x "$stock" || stock=$(readlink -f "$(command -v codex)"); test -x "$stock" || exit 1
mkdir -p "$state" "$data" "$HOME/.local/bin"
if test ! -e "$state/kind"; then if test -L "$bin"; then echo symlink >"$state/kind"; readlink "$bin" >"$state/target"; elif test -f "$bin"; then echo file >"$state/kind"; cp -p "$bin" "$state/original"; else echo missing >"$state/kind"; fi; fi
if test -d "$repo"; then "$stock" plugin marketplace add "$repo" >/dev/null 2>&1 || true; else "$stock" plugin marketplace add "$repo" --ref main >/dev/null 2>&1 || true; fi
"$stock" plugin marketplace upgrade compactveteran >/dev/null 2>&1 || true; j=$("$stock" plugin add compactveteran@compactveteran --json); root=$(printf '%s\n' "$j" | sed -n 's/.*"installedPath"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p'); test -n "$root" && test -d "$root"
t=$(mktemp "$data/.cv.XXXXXX"); trap 'rm -f "$t"' 0 1 2 3 15; if test -n "${COMPACTVETERAN_BINARY-}"; then cp "$COMPACTVETERAN_BINARY" "$t"; else curl -fsSL "https://github.com/$repo/releases/latest/download/compactveteran-x86_64-unknown-linux-gnu" -o "$t"; fi; chmod 0755 "$t"; mv -f "$t" "$data/compactveteran"; printf '%s\n' "$stock">"$state/stock-path"; PLUGIN_DATA="$data" "$data/compactveteran" refresh-catalog; PLUGIN_DATA="$data" "$data/compactveteran" install-config; PLUGIN_DATA="$data" "$data/compactveteran" trust
t=$(mktemp "$HOME/.local/bin/.codex.XXXXXX"); printf '%s\n' '#!/usr/bin/env bash' 'set -euo pipefail' 'logs="${XDG_STATE_HOME:-$HOME/.local/state}/codex-runtime-state/logs_2.sqlite"' 'if test -f "$logs" && test "$(stat -c %s "$logs")" -gt 536870912 && ! pgrep -u "$UID" -x codex >/dev/null; then archive="$(dirname "$logs")/log-archives/$(date -u +%Y%m%dT%H%M%SZ)"; mkdir -p "$archive"; for suffix in "" -wal -shm; do path="$logs$suffix"; test -e "$path" && mv "$path" "$archive/"; done; fi' 'exec "${CODEX_HOME:-$HOME/.codex}/plugins/data/compactveteran-compactveteran/compactveteran" supervisor "$@"' >"$t"; chmod 0755 "$t"; mv -f "$t" "$bin"; PLUGIN_DATA="$data" "$data/compactveteran" doctor; echo 'CompactVeteran installed. No context left behind.'
