use serde_json::{json,Value};
use sha2::{Digest,Sha256};
use std::{env,fs,io::{self,Read,Write},path::{Path,PathBuf},process::{Command,Stdio}};
const SOL:&str="gpt-5.6-sol"; const MSG:&str="Context compaction dodged.";
fn home()->PathBuf{env::var_os("CODEX_HOME").map(PathBuf::from).or_else(||env::var_os("HOME").map(|p|PathBuf::from(p).join(".codex"))).unwrap()}
fn state()->PathBuf{env::var_os("XDG_STATE_HOME").map(PathBuf::from).or_else(||env::var_os("HOME").map(|p|PathBuf::from(p).join(".local/state"))).unwrap().join("compactveteran")}
fn out(c:&mut Command)->io::Result<String>{let x=c.output()?;if !x.status.success(){return Err(io::Error::other(String::from_utf8_lossy(&x.stderr).into_owned()))}Ok(String::from_utf8_lossy(&x.stdout).trim().into())}
fn git(p:&Path,a:&[&str])->io::Result<String>{out(Command::new("git").arg("-C").arg(p).args(a))}
fn atomic(p:&Path,b:&[u8])->io::Result<()>{fs::create_dir_all(p.parent().unwrap())?;let t=p.with_extension("tmp");fs::write(&t,b)?;fs::rename(t,p)}
fn hash(b:&[u8])->String{let mut h=Sha256::new();h.update(b);format!("{:x}",h.finalize())}
fn event()->Value{let mut s=String::new();io::stdin().read_to_string(&mut s).ok();serde_json::from_str(&s).unwrap_or_default()}
fn root(c:&Path)->io::Result<PathBuf>{match git(c,&["rev-parse","--show-toplevel"]){Ok(x)=>Ok(x.into()),Err(_)=>{out(Command::new("git").args(["init","-b","main"]).arg(c))?;git(c,&["rev-parse","--show-toplevel"]).map(Into::into)}}}
fn sol(v:&Value)->bool{v.get("model").and_then(Value::as_str)==Some(SOL)&&v.get("agent_id").is_none()&&v.get("agent_type").is_none()}
fn checkpoint(v:&Value)->io::Result<PathBuf>{let cwd=PathBuf::from(v.get("cwd").and_then(Value::as_str).unwrap_or("."));let r=root(&cwd)?;let dirty=git(&r,&["status","--porcelain"])?;if !dirty.is_empty(){if git(&r,&["branch","--show-current"]).unwrap_or_default().is_empty(){return Err(io::Error::other("detached HEAD"));}for l in dirty.lines(){let p=l.get(3..).unwrap_or("").to_ascii_lowercase();if p.contains(".env")||p.contains("secret")||p.contains("credential")||p.ends_with(".pem")||p.ends_with(".key"){return Err(io::Error::other("credential filename guard"));}}out(Command::new("git").arg("-C").arg(&r).args(["add","-A"]))?;out(Command::new("git").arg("-C").arg(&r).args(["diff","--cached","--check"]))?;out(Command::new("git").arg("-C").arg(&r).args(["-c","user.name=CompactVeteran","-c","user.email=compactveteran@localhost","commit","-m","compactveteran: checkpoint turn"]))?;let up=git(&r,&["rev-parse","--abbrev-ref","--symbolic-full-name","@{u}"]).unwrap_or_default();if !up.is_empty(){out(Command::new("git").arg("-C").arg(&r).arg("push"))?;}}
let m=home().join("project-maps").join(format!("{}.md",hash(r.to_string_lossy().as_bytes())));let tr=v.get("transcript_path").and_then(Value::as_str).unwrap_or("");let tb=fs::read(tr).unwrap_or_default();let text=format!("# CompactVeteran\n\n- root: {}\n- remote: {}\n- branch: {}\n- upstream: {}\n- HEAD: {}\n- status: {}\n- transcript: {}\n- transcript_sha256: {}\n- session_lineage: {}\n- latest_user_directive: {}\n\n## recent commits\n{}\n\n## roadmap and sources\n{}\n\n## resume\nRead this map, inspect Git and referenced raw logs, and continue the unfinished work from HEAD.\n",r.display(),git(&r,&["remote","get-url","origin"]).unwrap_or_default(),git(&r,&["branch","--show-current"]).unwrap_or_default(),git(&r,&["rev-parse","--abbrev-ref","--symbolic-full-name","@{u}"]).unwrap_or_default(),git(&r,&["rev-parse","HEAD"]).unwrap_or_default(),git(&r,&["status","--porcelain"]).unwrap_or_default(),tr,hash(&tb),v.get("thread_id").and_then(Value::as_str).unwrap_or(""),v.get("prompt").and_then(Value::as_str).unwrap_or(""),git(&r,&["log","-10","--oneline"]).unwrap_or_default(),["ROADMAP.md","AGENTS.md","README.md"].iter().filter(|x|r.join(x).exists()).copied().collect::<Vec<_>>().join(", "));atomic(&m,text.as_bytes())?;Ok(m)}
fn overlay()->io::Result<PathBuf>{let mut v:Value=serde_json::from_str(&fs::read_to_string(home().join("models_cache.json"))?)?;let mut found=false;if let Some(a)=v.get_mut("models").and_then(Value::as_array_mut){for x in a{if x.get("slug").and_then(Value::as_str)==Some(SOL){found=true;let o=x.as_object_mut().unwrap();o.insert("context_window".into(),json!(1050000));o.insert("max_context_window".into(),json!(1050000));o.insert("auto_compact_token_limit".into(),json!(950000));}}}if !found{return Err(io::Error::other("gpt-5.6-sol missing"))}let p=state().join("models-overlay.json");atomic(&p,serde_json::to_vec(&v)?.as_slice())?;Ok(p)}
fn hook(k:&str){let v=event();if !sol(&v){println!("{}",json!({"continue":true}));return}if k=="prompt"{let p=state().join("sessions").join(v.get("thread_id").and_then(Value::as_str).unwrap_or("unknown"));atomic(&p,serde_json::to_vec(&v).unwrap().as_slice()).unwrap();println!("{}",json!({"continue":true}));return}match checkpoint(&v){Ok(m) if k=="precompact"=>{println!("{}",json!({"continue":false,"stopReason":MSG,"systemMessage":MSG,"map":m}));io::stdout().flush().ok();},Ok(_)=>println!("{}",json!({"continue":true})),Err(e)=>{eprintln!("CompactVeteran: {e}");println!("{}",json!({"continue":false,"stopReason":e.to_string()}));}}}
fn main(){let mut a=env::args().skip(1);match a.next().as_deref(){Some("refresh-catalog")|Some("overlay")=>println!("{}",overlay().unwrap().display()),Some("hook")=>hook(a.next().as_deref().unwrap_or("stop")),Some("supervisor")=>{let _=overlay();let mut c=Command::new(home().join("packages/standalone/current/bin/codex"));c.args(a).stdin(Stdio::inherit()).stdout(Stdio::inherit()).stderr(Stdio::inherit());std::process::exit(c.status().unwrap().code().unwrap_or(1))},_=>{}}}
